routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AddClassController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get("/",HomeController::class)->name('home');
Route::get("single-student/{id}",[HomeController::class,'singleStudent'])->name('student.single');

Route::resource('students', StudentsController::class);
Route::get("import-more",[StudentsController::class,'ImportFile'])->name('import.more');
Route::post("import-more",[StudentsController::class,'Import'])->name('import.add');



Route::resource('subject', SubjectController::class);


Route::resource('classes', AddClassController::class);
Route::get("class-to-student",[AddClassController::class,'classToStudent'])->name('classTOstudent.add');
Route::get("single-class/{id}",[AddClassController::class,'singleClass'])->name('single.class');
Route::post("class-student",[AddClassController::class,'classStudent'])->name('clasStudent.add');

Route::get("subject_add",[ReportController::class,'subjectAdd'])->name('subject.add');
Route::get("Import-Report",[ReportController::class,'reportImport'])->name('Import.Report');
Route::post("Import-add",[ReportController::class,'report'])->name('report.add');
Route::post("add_subject",[ReportController::class,'store'])->name('add.subject');

app/Http/Controllers/AddClassController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddClassRequest;
use App\Models\AddClass;
use App\Models\AllClass;
use App\Models\Students;
use Illuminate\Http\Request;

class AddClassController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['Class'] = AddClass::all();
        return view('AddClass.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddClassRequest $request)
    {
        $class = AddClass::create([
            "class_name" => $request->get('class_name'),
        ]);
        if ($class) {
            $notification = array(
                'messege' => 'Successfully Class Add !!!',
                'alert-type' => 'success'
            );
        } else {
            $notification = array(
                'messege' => 'Something went wrong !',
                'alert-type' => 'error'
            );
        }
        return back()->with($notification);
        // return redirect()->route('subject.index')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function classToStudent()
    {
        $data['student'] = Students::all();
        $data['class'] = AddClass::all();
        return view('AddClass.StudentToClass', $data);
    }

    public function classStudent(Request $request)
    {
        $data = new AllClass;
        $data->student_id = $request->student_id;
        $data->class_id = $request->class_id;
        $save = $data->save();
        if ($save) {
            $notification = array(
                'messege' => 'Successfully Class Add !!!',
                'alert-type' => 'success'
            );
        } else {
            $notification = array(
                'messege' => 'Something went wrong !',
                'alert-type' => 'error'
            );
        }
        return back()->with($notification);

    }

    public function singleClass($id)
    {

        $student_id = AllClass::where('class_id', $id)->get();
        $student_all = array();
        foreach ($student_id as $single) {
            $student = Students::where('id', $single->student_id)->get();
            $array = array(
                'student_id' => $single->student_id,
                'student_name' => $student,
            );
            array_push($student_all, $array);
        }
        //dd($student_all);
        return view('AddClass.classTostudent', compact('student_all'));
    }


}

resources/views/AddClass/StudentToClass.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Class To Student")}}</title>
@endsection
@section('cus_style')
    <!-- Plugins css -->
    <link href="{{asset('backend/libs/dropzone/min/dropzone.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('backend/libs/dropify/css/dropify.min.css')}}" rel="stylesheet" type="text/css"/>

    <!--dataTables-->
    <link rel="stylesheet" type="text/css" href="{{asset('backend/assets/libs/bootstrap-select/css/bootstrap-select.min.css')}}">
@endsection
@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title">{{__("Class To Student")}}</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        </h5>
                        <form method="post" action="{{route('clasStudent.add')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Class Name")}}</label>
                                        <select name="class_id" class="selectpicker" data-style="btn-outline-primary">
                                            <option value="0">Select Subject</option>
                                            @foreach($class as $key)
                                                <option value="{{$key->id}}">{{$key->class_name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Student Name")}}</label>
                                        <select name="student_id" class="selectpicker" data-style="btn-outline-primary">
                                            <option value="0">Select Student</option>
                                            @foreach($student as $key)
                                                <option value="{{$key->id}}">{{$key->student_name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="ladda-button btn btn-primary" dir="ltr"
                                            data-style="expand-right">
                                        {{__("Add ")}}
                                    </button>
                                </div>
                            </div> <!-- end row -->
                            <!-- end row-->
                        </form>
                    </div> <!-- end card-body -->
                </div> <!-- end card -->
            </div><!-- end col -->
        </div>
        <!-- end row -->


    </div> <!-- container -->

@endsection
@section('js')
    <!-- Plugins js -->
    <script src="{{asset('backend/libs/dropzone/min/dropzone.min.js')}}"></script>
    <script src="{{asset('backend/libs/dropify/js/dropify.min.js')}}"></script>
    <script src="{{asset('backend/js/pages/form-fileuploads.init.js')}}"></script>

    <!--dataTables-->
    <script type="text/javascript" charset="utf8"
            src="{{asset('backend/assets/js/dataTables.jqueryui.min.js')}}"></script>
    <script type="text/javascript" charset="utf8" src="{{asset('backend/assets/js/jquery.dataTables.js')}}"></script>

    <script src="{{asset('backend/assets/libs/bootstrap-select/js/bootstrap-select.min.js')}}"></script>


@endsection

resources/views/AddClass/classTostudent.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Class To Student")}}</title>
@endsection
@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title">{{__("Class To Student")}}</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <!-- end row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Class List</h4>
                        <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Student Name</th>
                            </tr>
                            </thead>
                            <tbody>
{{--{{dd($student_all)}}--}}
                            @foreach($student_all as $key)
                                <tr>
                                    <td>{{$key['student_id']}}</td>
{{--                                    <td>{{$key->student_name['student_name']}}</td>--}}
                                </tr>
                            @endforeach
                            </tbody>

                        </table>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>


    </div> <!-- container -->

@endsection

resources/views/AddClass/create.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Add Class")}}</title>
@endsection
@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title">{{__("Class Add")}}</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        </h5>
                        <form method="post" action="{{route('classes.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Class Name")}}</label>
                                        <input type="text" class="form-control" name="class_name"  required>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="ladda-button btn btn-primary" dir="ltr"
                                            data-style="expand-right">
                                        {{__("Add")}}
                                    </button>
                                </div>
                            </div> <!-- end row -->
                            <!-- end row-->
                        </form>
                    </div> <!-- end card-body -->
                </div> <!-- end card -->
            </div><!-- end col -->
        </div>
        <!-- end row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Class List</h4>
                        <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Class Name</th>
                                <th>Total Student</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $number = 0; ?>
                            @foreach($Class as $key)
                                <tr>
                                    <td>{{$number+1}}</td>
                                    <?php $number++;
                                    ?>
                                    <td>{{$key->class_name}}</td>
                                    @php
                                    $total=\App\Models\AllClass::where('class_id',$key->id)->groupBy('class_id')->count('student_id');
                                    @endphp
                                    <td>{{$total}}</td>
                                    <td>
                                        <a href="{{route('single.class',$key->id)}}" role="button" class="btn btn-danger">Detail</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>


    </div> <!-- container -->

@endsection
@section('js')
    <!-- Plugins js -->
    <script src="{{asset('backend/libs/dropzone/min/dropzone.min.js')}}"></script>
    <script src="{{asset('backend/libs/dropify/js/dropify.min.js')}}"></script>
    <script src="{{asset('backend/js/pages/form-fileuploads.init.js')}}"></script>

    <!--dataTables-->
    <script type="text/javascript" charset="utf8"
            src="{{asset('backend/assets/js/dataTables.jqueryui.min.js')}}"></script>
    <script type="text/javascript" charset="utf8" src="{{asset('backend/assets/js/jquery.dataTables.js')}}"></script>

    <script src="{{asset('backend/assets/libs/bootstrap-select/js/bootstrap-select.min.js')}}"></script>


@endsection