routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\StudentsController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AddClassController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get("/",HomeController::class)->name('home');
Route::get("single-student/{id}",[HomeController::class,'singleStudent'])->name('student.single');

Route::resource('students', StudentsController::class);
Route::get("import-more",[StudentsController::class,'ImportFile'])->name('import.more');
Route::post("import-more",[StudentsController::class,'Import'])->name('import.add');



Route::resource('subject', SubjectController::class);


Route::resource('classes', AddClassController::class);
Route::get("class-to-student",[AddClassController::class,'classToStudent'])->name('classTOstudent.add');
Route::get("single-class/{id}",[AddClassController::class,'singleClass'])->name('single.class');
Route::post("class-student",[AddClassController::class,'classStudent'])->name('clasStudent.add');

Route::get("subject_add",[ReportController::class,'subjectAdd'])->name('subject.add');
Route::get("Import-Report",[ReportController::class,'reportImport'])->name('Import.Report');
Route::post("Import-add",[ReportController::class,'report'])->name('report.add');
Route::post("add_subject",[ReportController::class,'store'])->name('add.subject');

app/Models/Students.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Students extends Model
{
    use HasFactory;
    protected $fillable = [
        'student_name',
        'student_father',
        'student_mother',
        'email',
    ];

    public function subjects(){
        return $this->belongsToMany(Subject::class);
    }
}

app/Http/Controllers/StudentsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentsRequest;
use App\Imports\StudentsDetailsImport;
use App\Imports\StudentsImport;
use App\Models\Report;
use App\Models\Students;
use Illuminate\Auth\Events\Validated;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Excel;

class StudentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data['student']=Students::all();
      return view('Students.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentsRequest $request)
    {

        $students= Students::create([
            "student_name"=>$request->get('student_name'),
            "student_father"=>$request->get('student_father'),
            "student_mother"=>$request->get('student_mother'),
            "email"=>$request->get('email'),
        ]);

        if ($students) {
            $notification = array(
                'messege' => 'Successfully Student Add !!!',
                'alert-type' => 'success'
            );
        } else {
            $notification = array(
                'messege' => 'Something went wrong !',
                'alert-type' => 'error'
            );
        }

        return redirect()->route('students.index')->with($notification);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function ImportFile(){

        return view('Students.Import');
    }


    public function Import(Request $request){
    $data_a=$request->validate([
            'file'=> 'required|mimes:xlsx,'
        ]);
        $file = $request->file('file')->store('import');
        $data= (new StudentsImport)->import($file);
        if ($data) {
            $notification = array(
                'messege' => 'Successfully Excel Add !!!',
                'alert-type' => 'success'
            );
        } else {
            $notification = array(
                'messege' => 'Something went wrong !',
                'alert-type' => 'error'
            );
            return back()->with($notification);
        }
        return redirect()->route('students.index')->with($notification);

    }
}

resources/views/Students/Import.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Add More")}}</title>
@endsection
@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title">{{__("Add More")}}</h4>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post" action="{{route('import.add')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Add File")}}</label>
                                        <input type="file" accept=".xlsx" placeholder="gududdgu" class="form-control"
                                               name="file" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="ladda-button btn btn-primary" dir="ltr"
                                            data-style="expand-right">
                                        {{__("Import")}}
                                    </button>
                                </div>
                            </div> <!-- end row -->
                            <!-- end row-->
                        </form>
                    </div> <!-- end card-body -->
                </div> <!-- end card -->
            </div><!-- end col -->
        </div>
        <!-- end row -->
    </div> <!-- container -->

@endsection

resources/views/Students/create.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Student Add")}}</title>
@endsection
@section('content')
    <div class="container-fluid">
        <!-- start page title -->
        <div class="row">
            <div class="col-6">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title">{{__("Student Info")}}</h4>
                </div>
            </div>
            <div class="col-6">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <a href="{{route('import.more')}}" class="page-title badge-danger">{{__("Import Student")}}</a>
                </div>
            </div>
        </div>
        <!-- end page title -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        </h5>
                        <form method="post" action="{{route('students.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Students Name")}}</label>
                                        <input type="text" class="form-control" name="student_name" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Students Father Name")}}</label>
                                        <input type="text" class="form-control" name="student_father" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Students Mother Name")}}</label>
                                        <input type="text" class="form-control" name="student_mother" required>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="firstname">{{__("Email")}}</label>
                                        <input type="text" class="form-control" name="email" required>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="ladda-button btn btn-primary" dir="ltr"
                                            data-style="expand-right">
                                        {{__("Add")}}
                                    </button>
                                </div>
                            </div> <!-- end row -->
                            <!-- end row-->
                        </form>
                    </div> <!-- end card-body -->
                </div> <!-- end card -->
            </div><!-- end col -->
        </div>
        <!-- end row -->


    </div> <!-- container -->

@endsection
@section('js')
    <!-- Plugins js -->
    <script src="{{asset('backend/libs/dropzone/min/dropzone.min.js')}}"></script>
    <script src="{{asset('backend/libs/dropify/js/dropify.min.js')}}"></script>
    <script src="{{asset('backend/js/pages/form-fileuploads.init.js')}}"></script>

    <!--dataTables-->
    <script type="text/javascript" charset="utf8" src="{{asset('backend/assets/js/dataTables.jqueryui.min.js')}}"></script>
    <script type="text/javascript" charset="utf8" src="{{asset('backend/assets/js/jquery.dataTables.js')}}"></script>


@endsection

resources/views/Students/index.blade.php
@extends('backend.master')
@section('title_a')
    <title>{{__("Student List")}}</title>
@endsection
@section('content')
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="header-title">Student List</h4>


                        <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Student Name</th>
                                <th>Student Father Name</th>
                                <th>Student Mother Name</th>
                                <th>Student Email</th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php $number = 0; ?>
                            @foreach($student as $key)
                                <tr>
                                    <td>{{$number+1}}</td>
                                    <?php $number++; ?>
                                    <td>{{$key->student_name}}</td>
                                    <td>{{$key->student_father}}</td>
                                    <td>{{$key->student_mother}}</td>
                                    <td>
                                        {{$key->email}}
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>

                    </div> <!-- end card body-->
                </div> <!-- end card -->
            </div><!-- end col-->
        </div>

    </div> <!-- container -->
@endsection
@section('js')



@endsection